# Split Training Tiles into Batches for Manual Editing

This script finds all of the training tile images needed for each batch of the ARTS polygon updating process.

## Set-Up

In [64]:
import os
from google.cloud import storage
import google.auth
import numpy as np
import pandas as pd
import geopandas as gpd
import shapely as shp
from pprint import pprint
import re
import itertools

In [ ]:
# Get GCS API Key
%load_ext dotenv
%dotenv

gcs_key = os.getenv("GCS_PL_ORDERS_KEY")

In [3]:
# ! gcloud auth login
gcloud_creds, _ = google.auth.default()

In [4]:
storage_client = storage.Client(project="AbruptThawMapping")
bucket_name = "abrupt_thaw"
bucket = storage_client.bucket(bucket_name)

## Import Data

In [ ]:
planet_grids = gpd.read_file(
    "../ARTS_metrics/data/planet_grids_2024_artsv.6.0.0_positive_polygons_stratified_random_order_by_region.geojson"  # or https://drive.google.com/file/d/1BdhvZrwUKd4vKJIehmpnuxqwlAXEwKT_/view?usp=drive_link
)
planet_grids

,year,id,grid_column,grid_row,basemap_name,delivery_location,link,original_order,region,n_tiles,expected_order_tiles,n_arts,expected_order_arts,stratified_random_order,chunk,geometry
0,2024,44-1514,44,1514,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/44/1514/,https://link.planet.com/basemaps/v1/mosaics/44...,155,1,117.0,5.0,759,8,1,1.0,"POLYGON ((-19156953.777 9588260.828, -19156953..."
1,2024,116-1560,116,1560,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/116/1...,https://link.planet.com/basemaps/v1/mosaics/44...,436,2,611.0,12.0,1420,11,2,1.0,"POLYGON ((-17748066.472 10488383.273, -1774806..."
2,2024,257-1533,257,1533,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/257/1...,https://link.planet.com/basemaps/v1/mosaics/44...,2003,3,2468.0,15.0,7190,18,3,1.0,"POLYGON ((-14988995.499 9960050.534, -14988995..."
3,2024,333-1613,333,1613,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/333/1...,https://link.planet.com/basemaps/v1/mosaics/44...,3400,4,3180.0,16.0,10878,19,4,1.0,"POLYGON ((-13501836.676 11525480.873, -1350183..."
4,2024,397-1513,397,1513,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/397/1...,https://link.planet.com/basemaps/v1/mosaics/44...,4613,5,81.0,4.0,210,3,5,1.0,"POLYGON ((-12249492.405 9568692.949, -12249492..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2989,2024,356-1647,356,1647,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/356/1...,https://link.planet.com/basemaps/v1/mosaics/44...,4065,4,3180.0,16.0,10878,19,2990,299.0,"POLYGON ((-13051775.454 12190788.767, -1305177..."
2990,2024,349-1643,349,1643,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/349/1...,https://link.planet.com/basemaps/v1/mosaics/44...,3893,4,3180.0,16.0,10878,19,2991,300.0,"POLYGON ((-13188750.608 12112517.25, -13188750..."
2991,2024,350-1640,350,1640,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/350/1...,https://link.planet.com/basemaps/v1/mosaics/44...,3918,4,3180.0,16.0,10878,19,2992,300.0,"POLYGON ((-13169182.729 12053813.612, -1316918..."
2992,2024,308-1567,308,1567,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/308/1...,https://link.planet.com/basemaps/v1/mosaics/44...,2908,4,3180.0,16.0,10878,19,2993,300.0,"POLYGON ((-13991033.657 10625358.428, -1399103..."
2993,2024,356-1648,356,1648,global_quarterly_2024q3_mosaic,planet_basemaps/global_quarterly/2024/q3/356/1...,https://link.planet.com/basemaps/v1/mosaics/44...,4066,4,3180.0,16.0,10878,19,2994,300.0,"POLYGON ((-13051775.454 12210356.646, -1305177..."

In [ ]:
training_tile_prefix = ("RTS_MODEL_V2/DATA/TEST/")
training_tile_directory = "gs://" + bucket_name + "/" + training_tile_prefix
blobs = bucket.list_blobs(prefix = training_tile_prefix)
files = [file for file in blobs if re.search(".tif", file.name)]
file_names = [file.name for file in files]

[<Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/10/1547/tile_10_1547_c5_r0.tif, 1763571824948030>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/10/1549/tile_10_1549_c2_r0.tif, 1763571828640210>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/10/1549/tile_10_1549_c3_r0.tif, 1763571828111622>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/10/1549/tile_10_1549_c4_r0.tif, 1763571828374077>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/10/1550/tile_10_1550_c2_r7.tif, 1763571829512102>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/10/1550/tile_10_1550_c3_r7.tif, 1763571829227434>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/100/1557/tile_100_1557_c2_r7.tif, 1763571836817976>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/100/1557/tile_100_1557_c3_r7.tif, 1763571836559765>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/101/1557/tile_101_1557_c4_r6.tif, 1763571846178428>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/101/1557/tile_101_1557_c5_r6.tif, 1763571845919790>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/102/1556/tile_102_1556_c4_r1.tif, 1763571854555397>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1551/tile_103_1551_c5_r5.tif, 1763571870579062>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1551/tile_103_1551_c7_r2.tif, 1763571870308528>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1553/tile_103_1553_c3_r5.tif, 1763571871720211>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1557/tile_103_1557_c0_r2.tif, 1763571876036957>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1557/tile_103_1557_c1_r2.tif, 1763571874961161>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1557/tile_103_1557_c4_r3.tif, 1763571875241978>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1557/tile_103_1557_c4_r4.tif, 1763571875773571>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/103/1557/tile_103_1557_c6_r5.tif, 1763571875503732>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1551/tile_104_1551_c4_r2.tif, 1763571887043509>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1551/tile_104_1551_c5_r1.tif, 1763571886523579>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1551/tile_104_1551_c5_r2.tif, 1763571886774400>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1552/tile_104_1552_c4_r1.tif, 1763571888947736>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1552/tile_104_1552_c5_r0.tif, 1763571890030354>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1552/tile_104_1552_c5_r3.tif, 1763571889219897>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1552/tile_104_1552_c6_r0.tif, 1763571890295384>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1552/tile_104_1552_c6_r4.tif, 1763571889762320>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1552/tile_104_1552_c6_r7.tif, 1763571889519243>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1553/tile_104_1553_c0_r4.tif, 1763571890834995>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1553/tile_104_1553_c7_r2.tif, 1763571890323159>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1553/tile_104_1553_c7_r5.tif, 1763571890587613>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1556/tile_104_1556_c1_r1.tif, 1763571892199225>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/104/1557/tile_104_1557_c1_r4.tif, 1763571895515449>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1551/tile_105_1551_c0_r0.tif, 1763571906540603>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1552/tile_105_1552_c0_r7.tif, 1763571907716963>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1552/tile_105_1552_c1_r1.tif, 1763571908001135>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c0_r2.tif, 1763571911477553>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c0_r7.tif, 1763571912031587>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c3_r2.tif, 1763571910100677>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c4_r7.tif, 1763571912303849>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c5_r6.tif, 1763571910387406>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c6_r4.tif, 1763571911744558>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c6_r5.tif, 1763571911209320>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c7_r1.tif, 1763571910928190>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1553/tile_105_1553_c7_r2.tif, 1763571910664599>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1554/tile_105_1554_c7_r6.tif, 1763571912414715>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1557/tile_105_1557_c3_r5.tif, 1763571915803315>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1557/tile_105_1557_c4_r0.tif, 1763571916068502>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1562/tile_105_1562_c6_r1.tif, 1763571918388159>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/105/1562/tile_105_1562_c7_r1.tif, 1763571918136801>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1553/tile_106_1553_c2_r0.tif, 1763571929461148>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1553/tile_106_1553_c2_r1.tif, 1763571929729290>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1553/tile_106_1553_c2_r2.tif, 1763571930026565>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1553/tile_106_1553_c7_r0.tif, 1763571929179965>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1554/tile_106_1554_c6_r4.tif, 1763571932164647>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1555/tile_106_1555_c1_r1.tif, 1763571935384998>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1555/tile_106_1555_c1_r2.tif, 1763571935929824>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1555/tile_106_1555_c1_r3.tif, 1763571936205357>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1555/tile_106_1555_c2_r1.tif, 1763571936468668>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1555/tile_106_1555_c2_r2.tif, 1763571935657477>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1557/tile_106_1557_c2_r1.tif, 1763571936099218>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1557/tile_106_1557_c3_r1.tif, 1763571936362465>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1557/tile_106_1557_c6_r1.tif, 1763571936642540>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/106/1562/tile_106_1562_c0_r5.tif, 1763571937987748>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/107/1553/tile_107_1553_c5_r2.tif, 1763571973281104>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/107/1557/tile_107_1557_c3_r5.tif, 1763571976394573>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/107/1557/tile_107_1557_c3_r6.tif, 1763571975835750>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/107/1557/tile_107_1557_c4_r7.tif, 1763571976101213>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/107/1560/tile_107_1560_c0_r1.tif, 1763571977046810>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/108/1556/tile_108_1556_c4_r2.tif, 1763572016590221>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/108/1556/tile_108_1556_c4_r5.tif, 1763572016854610>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/108/1556/tile_108_1556_c5_r3.tif, 1763572017117711>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/108/1564/tile_108_1564_c7_r5.tif, 1763572018858013>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1554/tile_109_1554_c5_r2.tif, 1763572071454804>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1554/tile_109_1554_c6_r3.tif, 1763572071709618>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1555/tile_109_1555_c5_r4.tif, 1763572073165224>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1556/tile_109_1556_c0_r4.tif, 1763572076333236>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1556/tile_109_1556_c0_r6.tif, 1763572076056989>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1556/tile_109_1556_c1_r5.tif, 1763572076600507>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1556/tile_109_1556_c2_r4.tif, 1763572075792510>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1556/tile_109_1556_c5_r3.tif, 1763572075529032>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1556/tile_109_1556_c5_r4.tif, 1763572075274159>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1558/tile_109_1558_c2_r3.tif, 1763572076984775>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1558/tile_109_1558_c2_r4.tif, 1763572076713382>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1558/tile_109_1558_c3_r1.tif, 1763572076450242>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/109/1558/tile_109_1558_c3_r4.tif, 1763572077256066>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/11/1549/tile_11_1549_c0_r5.tif, 1763572097744227>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/11/1549/tile_11_1549_c0_r6.tif, 1763572097195131>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/11/1549/tile_11_1549_c5_r5.tif, 1763572097469690>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/110/1554/tile_110_1554_c3_r0.tif, 1763572114551109>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/110/1555/tile_110_1555_c2_r6.tif, 1763572117912574>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/110/1555/tile_110_1555_c2_r7.tif, 1763572118224382>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/110/1555/tile_110_1555_c3_r7.tif, 1763572118479776>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/110/1556/tile_110_1556_c1_r7.tif, 1763572118626099>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/111/1553/tile_111_1553_c1_r6.tif, 1763572162320703>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/111/1556/tile_111_1556_c0_r4.tif, 1763572165840965>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/111/1556/tile_111_1556_c1_r4.tif, 1763572166115298>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/111/1556/tile_111_1556_c6_r6.tif, 1763572166391495>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/112/1556/tile_112_1556_c4_r0.tif, 1763572202509407>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/112/1557/tile_112_1557_c2_r3.tif, 1763572205185211>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/112/1557/tile_112_1557_c2_r4.tif, 1763572204925445>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/112/1557/tile_112_1557_c4_r6.tif, 1763572205441286>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/112/1557/tile_112_1557_c6_r0.tif, 1763572205953287>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/112/1557/tile_112_1557_c6_r1.tif, 1763572205701370>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/113/1566/tile_113_1566_c1_r6.tif, 1763572259355991>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/113/1566/tile_113_1566_c1_r7.tif, 1763572259610576>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/114/1556/tile_114_1556_c5_r2.tif, 1763572301206539>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/114/1557/tile_114_1557_c5_r7.tif, 1763572302415139>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/115/1557/tile_115_1557_c4_r7.tif, 1763572357462855>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/115/1558/tile_115_1558_c6_r2.tif, 1763572358910689>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/116/1560/tile_116_1560_c2_r1.tif, 1763572398230653>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/116/1560/tile_116_1560_c5_r0.tif, 1763572397961725>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/116/1560/tile_116_1560_c6_r0.tif, 1763572397683782>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/116/1561/tile_116_1561_c6_r7.tif, 1763572399524836>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/117/1558/tile_117_1558_c6_r4.tif, 1763572457349913>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/117/1559/tile_117_1559_c4_r6.tif, 1763572458466130>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/117/1559/tile_117_1559_c5_r6.tif, 1763572458735815>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/117/1588/tile_117_1588_c6_r6.tif, 1763572460213085>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/117/1588/tile_117_1588_c6_r7.tif, 1763572460503439>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1554/tile_118_1554_c2_r0.tif, 1763572480235888>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1558/tile_118_1558_c0_r0.tif, 1763572484385209>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1558/tile_118_1558_c0_r5.tif, 1763572485195176>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1558/tile_118_1558_c0_r6.tif, 1763572485473303>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1558/tile_118_1558_c0_r7.tif, 1763572484917035>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1558/tile_118_1558_c1_r5.tif, 1763572485756215>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1558/tile_118_1558_c1_r6.tif, 1763572484650962>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/118/1559/tile_118_1559_c3_r6.tif, 1763572486710027>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/119/1544/tile_119_1544_c1_r1.tif, 1763572516995412>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/12/1532/tile_12_1532_c1_r1.tif, 1763572536869057>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/12/1546/tile_12_1546_c0_r2.tif, 1763572538572738>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/12/1546/tile_12_1546_c1_r2.tif, 1763572538296139>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/12/1548/tile_12_1548_c7_r1.tif, 1763572541771800>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1543/tile_121_1543_c1_r4.tif, 1763572575500757>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1543/tile_121_1543_c2_r4.tif, 1763572575765681>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1553/tile_121_1553_c2_r1.tif, 1763572583381169>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1553/tile_121_1553_c3_r1.tif, 1763572583117264>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1553/tile_121_1553_c5_r1.tif, 1763572582842550>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1558/tile_121_1558_c0_r6.tif, 1763572584866141>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1558/tile_121_1558_c1_r6.tif, 1763572585415055>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1558/tile_121_1558_c7_r2.tif, 1763572585139659>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/121/1559/tile_121_1559_c4_r6.tif, 1763572585300150>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/122/1554/tile_122_1554_c3_r1.tif, 1763572604274106>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/122/1554/tile_122_1554_c3_r2.tif, 1763572603994613>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/122/1557/tile_122_1557_c1_r3.tif, 1763572608293327>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/122/1557/tile_122_1557_c1_r4.tif, 1763572608012153>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/122/1557/tile_122_1557_c3_r6.tif, 1763572608568989>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/122/1558/tile_122_1558_c1_r4.tif, 1763572608927241>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1554/tile_123_1554_c2_r2.tif, 1763572631576880>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1554/tile_123_1554_c2_r3.tif, 1763572631836099>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1555/tile_123_1555_c2_r2.tif, 1763572633526768>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1555/tile_123_1555_c4_r2.tif, 1763572633278382>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1561/tile_123_1561_c1_r4.tif, 1763572634307393>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1561/tile_123_1561_c2_r4.tif, 1763572634552545>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/123/1561/tile_123_1561_c2_r5.tif, 1763572634060972>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/124/1553/tile_124_1553_c2_r1.tif, 1763572664840916>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/124/1556/tile_124_1556_c6_r4.tif, 1763572667797907>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/124/1556/tile_124_1556_c6_r5.tif, 1763572667992901>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/124/1559/tile_124_1559_c7_r6.tif, 1763572669549637>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1552/tile_125_1552_c7_r0.tif, 1763572709667458>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1553/tile_125_1553_c4_r4.tif, 1763572710798945>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1554/tile_125_1554_c1_r1.tif, 1763572713835040>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1554/tile_125_1554_c1_r2.tif, 1763572713223478>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1554/tile_125_1554_c2_r0.tif, 1763572713424835>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1554/tile_125_1554_c5_r0.tif, 1763572713023431>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1554/tile_125_1554_c6_r0.tif, 1763572713622806>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1556/tile_125_1556_c0_r2.tif, 1763572714679918>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1558/tile_125_1558_c7_r5.tif, 1763572716993426>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1559/tile_125_1559_c0_r6.tif, 1763572718606068>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1561/tile_125_1561_c7_r2.tif, 1763572721102179>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1562/tile_125_1562_c6_r1.tif, 1763572723985741>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1562/tile_125_1562_c6_r7.tif, 1763572724402422>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/125/1562/tile_125_1562_c7_r7.tif, 1763572724192928>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1552/tile_126_1552_c0_r0.tif, 1763572761294145>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1557/tile_126_1557_c4_r1.tif, 1763572763163324>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1557/tile_126_1557_c7_r2.tif, 1763572763355021>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1558/tile_126_1558_c3_r1.tif, 1763572766034375>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1558/tile_126_1558_c5_r4.tif, 1763572765834884>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1558/tile_126_1558_c5_r5.tif, 1763572766232505>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c0_r2.tif, 1763572772615562>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c0_r3.tif, 1763572773663118>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c1_r1.tif, 1763572771958739>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c1_r3.tif, 1763572773249581>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c2_r1.tif, 1763572772193577>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c5_r3.tif, 1763572773457642>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c6_r3.tif, 1763572772829406>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c7_r1.tif, 1763572773037196>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1561/tile_126_1561_c7_r2.tif, 1763572772411338>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/126/1562/tile_126_1562_c2_r6.tif, 1763572771441985>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1535/tile_127_1535_c2_r1.tif, 1763572790443447>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1535/tile_127_1535_c3_r1.tif, 1763572790215087>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1554/tile_127_1554_c0_r3.tif, 1763572792735420>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1555/tile_127_1555_c6_r1.tif, 1763572794330007>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1555/tile_127_1555_c7_r1.tif, 1763572794521844>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1556/tile_127_1556_c6_r7.tif, 1763572796232979>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1556/tile_127_1556_c7_r1.tif, 1763572796036121>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1558/tile_127_1558_c5_r0.tif, 1763572799877938>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1559/tile_127_1559_c2_r7.tif, 1763572803328595>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1559/tile_127_1559_c3_r7.tif, 1763572803748864>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1559/tile_127_1559_c4_r7.tif, 1763572803554528>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1559/tile_127_1559_c5_r7.tif, 1763572803114137>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1559/tile_127_1559_c6_r7.tif, 1763572802904852>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/127/1560/tile_127_1560_c5_r4.tif, 1763572805892111>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/1271/1567/tile_1271_1567_c3_r0.tif, 1763572811618729>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/1271/1567/tile_1271_1567_c4_r0.tif, 1763572811819586>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/1271/1567/tile_1271_1567_c5_r0.tif, 1763572812402550>,
 <Blob: abrupt_thaw, RTS_MODEL_V2/DATA/TEST/1271/1567/tile_1271_1567_c6_r0.tif, 1763572812215771>,

## Get Training Tiles for Each Batch

In [95]:
batches = planet_grids.chunk.astype(int).unique()

# training tile positions within Planet grid that are of interest - order matches output in adjacent_grids
tile_positions = [
    "c7_r0",
    "c7_r.",
    "c7_r7",
    "c._r7",
    "c0_r7",
    "c0_r.",
    "c0_r0",
    "c._r0"
]

# data frame to store output
training_tiles_df = pd.DataFrame(columns=["batch", "grid_id", "training_tile"])

for batch in batches:
    # print("--------------------------------------------")

    # get Planet grid IDs included in batch
    grid_ids = planet_grids[planet_grids.chunk == batch].id
    grid_ids = [id.replace("-", "_") for id in grid_ids]
    # print("All Grid IDs:", grid_ids)

    # Create empty list to keep training tile blobs in
    training_tiles = []
    
    # # Get all training tiles within the grid
    # patterns = "|".join(grid_ids)
    # contained_training_tiles = [file for file in files if re.search(patterns, file.name)]
    # # pprint(contained_training_tiles)

    # # Missing training tiles?
    # training_tile_grid_ids = list(pd.Series(
    #     [re.search("\\d{1,4}_\\d{1,4}", file.name).group(0) for file in contained_training_tiles]
    # ).unique())
    # print("Grid IDs in Training Tile File Names:", training_tile_grid_ids)
    # patterns = "|".join(training_tile_grid_ids)
    # missing_grids = [grid_id for grid_id in grid_ids if not re.search(patterns, grid_id)]
    # print("Missing IDs:", missing_grids)

    # Get all contained and adjacent training tiles
    for grid_id in grid_ids:

        # Get all contained training tiles (within the grid)
        contained_training_tiles = [file for file in files if re.search(grid_id, file.name)]
        # pprint(contained_training_tiles)
        
        # Get all adjacent training tiles
        # possible Planet columns in which adjacent training tiles may occur
        planet_column = int(grid_id.split("_")[0])
        planet_columns = list(range(planet_column - 1, planet_column + 2))
        # print(planet_columns)

        # possible Planet rows in which adjacent training tiles may occur
        planet_row = int(grid_id.split("_")[1])
        planet_rows = list(range(planet_row - 1, planet_row + 2))
        # print(planet_rows)

        # select only the training tiles immediately adjacent to the current Planet grid
        adjacent_grid_ids = ["_".join([str(element) for element in combo]) for combo in itertools.product(planet_columns, planet_rows)]
        adjacent_tile_ids = [
            grid + "_" + tile for grid, tile in zip(adjacent_grid_ids, tile_positions)
        ]
        # print(adjacent_tile_ids)

        # Get all training tiles that match
        patterns = "|".join(adjacent_tile_ids)
        # print(patterns)
        adjacent_training_tiles = [
            file
            for file in files
            if re.search(patterns, file.name)
        ]
        # pprint(adjacent_training_tiles)

        current_tiles = contained_training_tiles + adjacent_training_tiles
        training_tiles = training_tiles + current_tiles

        training_tiles_df = pd.concat(
            [
                training_tiles_df,
                pd.DataFrame(
                    {
                        "batch": batch,
                        "grid_id": grid_id,
                        "training_tile": [current_tile.name for current_tile in current_tiles],
                    }
                ),
            ]
        )

   # training_tiles can be used to read in all of the tifs and merge them into one file

# training_tiles_df contains all the relevant imagery training_tiles for the current Planet grid
training_tiles_df.to_csv("./data/training_tiles_by_batch.csv", index = False)
training_tiles_df

   batch   grid_id                                      training_tile
0      1   44_1514  RTS_MODEL_V2/DATA/TEST/44/1514/tile_44_1514_c0...
1      1   44_1514  RTS_MODEL_V2/DATA/TEST/44/1514/tile_44_1514_c0...
2      1   44_1514  RTS_MODEL_V2/DATA/TEST/44/1514/tile_44_1514_c1...
3      1   44_1514  RTS_MODEL_V2/DATA/TEST/43/1514/tile_43_1514_c7...
4      1   44_1514  RTS_MODEL_V2/DATA/TEST/43/1514/tile_43_1514_c7...
..   ...       ...                                                ...
11   300  350_1640  RTS_MODEL_V2/DATA/TEST/349/1640/tile_349_1640_...
12   300  350_1640  RTS_MODEL_V2/DATA/TEST/349/1640/tile_349_1640_...
13   300  350_1640  RTS_MODEL_V2/DATA/TEST/349/1640/tile_349_1640_...
0    300  308_1567  RTS_MODEL_V2/DATA/TEST/308/1567/tile_308_1567_...
1    300  308_1567  RTS_MODEL_V2/DATA/TEST/308/1567/tile_308_1567_...

[14373 rows x 3 columns]